name: automerge
on:
  workflow_run:
    workflows: ["Test and build"]
    types: 
      - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      checks: write # allows dependabot PRs to set pull request checks
      contents: read
      pull-requests: write
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.13.0"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          MERGE_LABELS: "dependencies"
          MERGE_METHOD: "rebase"
          UPDATE_METHOD: "rebase"
          UPDATE_RETRIES : 10
          UPDATE_RETRY_SLEEP: 30
