name: Test and build
on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write # allows dependabot PRs to set pull request checks
      contents: read
      pull-requests: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Use Node.js 14.x
      uses: actions/setup-node@v4
      with:
        node-version: 14.x
    - name: Run 'npm install'
      run: npm install
    - name: Run tests
      run: npm test
    - name: Publish unit test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: junit.xml
